const std = @import("std");
pub const header = "// Generated by uca-maps-zig from Unicode 18.0.0 and CLDR 49 beta2. Do not edit.\n// Unicode data license: https://www.unicode.org/license.txt\n";
pub fn save(io: std.Io, alloc: std.mem.Allocator, path: []const u8, source: []const u8) !void {
    const terminated = try alloc.dupeSentinel(u8, source, 0);
    defer alloc.free(terminated);
    var ast = try std.zig.Ast.parse(alloc, terminated, .{});
    defer ast.deinit(alloc);
    if (ast.errors.len != 0) return error.InvalidGeneratedSource;
    const formatted = try ast.renderAlloc(alloc);
    defer alloc.free(formatted);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = formatted });
}

pub fn array(w: *std.Io.Writer, comptime T: type, name: []const u8, values: []const T) !void {
    try w.print("pub const {s} = [{d}]{s}{{\n", .{ name, values.len, @typeName(T) });
    for (values, 0..) |value, i| {
        try w.print("{d},", .{value});
        try w.writeAll(if (i % 16 == 15) "\n" else " ");
    }
    try w.writeAll("};\n");
}
